global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'django-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name:       'django'
    static_configs:
      - targets: ['localhost:8001', 'localhost:8002', 'localhost:8003']
